{% set version = "1.1.4" %}

package:
  name: bgenix
  version: "{{ version|replace("-", "_") }}"

source:
  url: https://github.com/huntdatacenter/rbgen/releases/download/{{ version }}/bgen-{{ version }}.tar.bz2
  sha256: c35c67e804ddb70a9bc0261ad8f02f32187b210c6dc3316312cab508c3bea7ce

build:
  skip: true  # [win]
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost {{ boost }}
    - boost-cpp {{ boost }}
    - sqlite
    - zlib
    - zstd
  run:
    - boost-cpp {{ boost }}

test:
  source_files:
    - example/example.15bits.bgen
    - example/example.16bits.bgen
    - example/example.16bits.bgen.bgi
  commands:
    - bgenix -help
    - bgenix -g example/example.16bits.bgen >/dev/null
    - bgenix -g example/example.15bits.bgen -index

about:
  home: https://enkre.net/cgi-bin/code/bgen
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: 'Reference implementation of the BGEN format, written in C++.'
  description: |
    Reference implementation of the BGEN format, written in C++.
    The library can be used as the basis for BGEN support
    in other software, or as a reference for developers
    writing their own implementations of the BGEN format.

    Band, G. and Marchini, J., "BGEN: a binary file format for imputed genotype
    and haplotype data", bioArxiv 308296; doi: https://doi.org/10.1101/308296
  dev_url: https://enkre.net/cgi-bin/code/bgen
  doc_url: https://enkre.net/cgi-bin/code/bgen/wcontent

extra:
  recipe-maintainers:
    - matuskosut
